In [1]:
## https://www.youtube.com/watch?v=ZspR5PZemcs&feature=youtu.be

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Importing Dataset
df = pd.read_csv("spotify.csv",index_col = [0]) 

In [4]:
df.head()

song_1  song_2  song_3  song_4  song_5  song_6  song_7  song_8  \
user_1       2       2       8       8      13       1       4       9   
user_2      13       5       5       5      12       8      10      10   
user_3       3       9       2       8       0       1      11       7   
user_4       2       6       7       8      14       0      12       7   
user_5      11      12       8       6      13       7       0       7   

        song_9  song_10  ...  song_4991  song_4992  song_4993  song_4994  \
user_1       1        2  ...         14          2         14          1   
user_2       2        2  ...         10          6         11          1   
user_3       3        7  ...          9          5          7         15   
user_4       8        1  ...          9         15          9         14   
user_5       3       13  ...         12         14         11         11   

        song_4995  song_4996  song_4997  song_4998  song_4999  song_5000  
user_1          9          0         11          6         14          7  
user_2          1          5         12          8          3          0  
user_3         12         13         14          5          0         14  
user_4         10          6         11         13          6          0  
user_5         11          7          3          6         11          7  

[5 rows x 5000 columns]

In [5]:
print("number of columns",len(df))
print("number of rows",len(df.columns))

number of columns 1000
number of rows 5000


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, user_1 to user_1000
Columns: 5000 entries, song_1 to song_5000
dtypes: int64(5000)
memory usage: 38.2+ MB


In [7]:
df.isnull().sum()

song_1       0
song_2       0
song_3       0
song_4       0
song_5       0
song_6       0
song_7       0
song_8       0
song_9       0
song_10      0
song_11      0
song_12      0
song_13      0
song_14      0
song_15      0
song_16      0
song_17      0
song_18      0
song_19      0
song_20      0
song_21      0
song_22      0
song_23      0
song_24      0
song_25      0
song_26      0
song_27      0
song_28      0
song_29      0
song_30      0
            ..
song_4971    0
song_4972    0
song_4973    0
song_4974    0
song_4975    0
song_4976    0
song_4977    0
song_4978    0
song_4979    0
song_4980    0
song_4981    0
song_4982    0
song_4983    0
song_4984    0
song_4985    0
song_4986    0
song_4987    0
song_4988    0
song_4989    0
song_4990    0
song_4991    0
song_4992    0
song_4993    0
song_4994    0
song_4995    0
song_4996    0
song_4997    0
song_4998    0
song_4999    0
song_5000    0
Length: 5000, dtype: int64

In [8]:
# Q.1 Which are top 5 songs heard by user 10
x = df.iloc[9,:]
x

song_1       12
song_2        3
song_3       10
song_4        4
song_5        0
song_6        1
song_7       12
song_8       10
song_9        7
song_10       5
song_11       4
song_12       7
song_13       0
song_14      10
song_15       0
song_16       3
song_17       5
song_18      11
song_19      15
song_20      15
song_21       5
song_22      13
song_23      14
song_24       3
song_25       2
song_26      10
song_27      12
song_28       2
song_29       0
song_30       9
             ..
song_4971     3
song_4972     8
song_4973    14
song_4974     8
song_4975     7
song_4976     2
song_4977    10
song_4978     1
song_4979     7
song_4980    11
song_4981    15
song_4982     5
song_4983     9
song_4984     0
song_4985     7
song_4986     8
song_4987    13
song_4988     7
song_4989    11
song_4990    11
song_4991    14
song_4992    10
song_4993     1
song_4994    15
song_4995     1
song_4996     7
song_4997     5
song_4998    10
song_4999    13
song_5000    14
Name: user_10, Length: 5

In [9]:
np.argsort(df.iloc[9,:].values)

array([2280, 1212, 1954, ..., 2085, 1986, 4390], dtype=int64)

In [10]:
# Q.2 Which are top 5 heard songs


In [11]:
# Convert into Numpy Array to perform Matrix Operation
X = np.array(df)

In [12]:
X.shape

(1000, 5000)

In [13]:
X

array([[ 2,  2,  8, ...,  6, 14,  7],
       [13,  5,  5, ...,  8,  3,  0],
       [ 3,  9,  2, ...,  5,  0, 14],
       ...,
       [ 6,  2,  1, ..., 13,  6, 13],
       [ 7,  0,  8, ..., 11,  9, 12],
       [ 6, 15,  0, ..., 15,  4,  5]], dtype=int64)

In [14]:
# Decompose the user song matrix into user matrix and song matrix
# Algorithm- NMF -Non negative Matrix Factorzation

In [15]:
from sklearn.decomposition import NMF

In [16]:
nmf = NMF(n_components= 100, max_iter= 50, random_state= 0)
nmf.fit(X)

NMF(alpha=0.0, beta_loss='frobenius', init=None, l1_ratio=0.0, max_iter=50,
  n_components=100, random_state=0, shuffle=False, solver='cd', tol=0.0001,
  verbose=0)

In [17]:
# Extracting Components of Row/User Matrix 
user_matrix = nmf.transform(X)

In [18]:
user_matrix.shape

(1000, 100)

In [19]:
user_matrix[0]

array([1.69203641e+00, 6.06332065e-02, 0.00000000e+00, 8.13628465e-01,
       1.39890281e+00, 0.00000000e+00, 9.78953027e-01, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 2.52894427e+00, 1.55913229e+00,
       0.00000000e+00, 1.23133122e+00, 1.29119922e-01, 2.67213682e-03,
       1.04063989e-01, 0.00000000e+00, 1.94633651e+00, 0.00000000e+00,
       1.97875532e+00, 0.00000000e+00, 2.54497254e+00, 1.00914138e+00,
       0.00000000e+00, 2.40786219e+00, 0.00000000e+00, 2.02945799e+00,
       0.00000000e+00, 1.03086289e-01, 3.37495589e+00, 1.83250348e+00,
       2.61682332e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.31686358e-01,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.42039683e-01,
       0.00000000e+00, 0.00000000e+00, 1.18281146e-01, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [20]:
song_matrix = nmf.components_

In [21]:
song_matrix.shape

(100, 5000)

In [22]:
song_matrix = song_matrix.T

In [23]:
song_matrix.shape

(5000, 100)

In [24]:
# Above part of Data Processing

# Building Recommendation Engine

## Step 1 - Find the Euclidian Distance between given user and all the other user
## Step 2 - Find 5 closest user
## Step 3 - Find songs that these 5 closest user listen to
## Step 4 - Recommend these songs to user

In [25]:
def euclidian_dist(v1,v2):
    return pow(sum([pow(v1[idx]-v2[idx],2) for idx in range(len(v1))]),0.5)

In [26]:
euclidian_dist(user_matrix[0],user_matrix[1])

12.682546952084659

In [27]:
user1_vec = user_matrix[0]

In [28]:
eucl_dist = []

In [29]:
for idx in range(1000):
    other_user = user_matrix[idx]
    eu = euclidian_dist(user1_vec,other_user)
    eucl_dist.append(eu)

In [30]:
candidate_index = np.argsort(eucl_dist)

In [31]:
candidate_index[1:6]

array([352, 737, 284, 501, 609], dtype=int64)

# Finding Eucledian distance between the given users to all the users

In [32]:
# Finding Euclidian distance between given user to all user
import sys
eucl_dist1 = list()
user1_id = 0 
counter = 0

In [33]:
for any_user in user_matrix[:]:
    if user1_id == counter:
        eucl_dist1.append(sys.float_info.max)
    else:
        user1 = user_matrix[0]
        dist = euclidian_dist(user1, any_user)
        eucl_dist1.append(dist)
counter += 1

eucl_dist1

[1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.7976931348623157e+308,
 1.797693134

In [34]:
closest_user_indices = [np.argsort(eucl_dist1)[:5]]
closest_user_indices

[array([  0, 658, 659, 660, 661], dtype=int64)]

In [35]:
# What songs do this 5 people listen to
for idx in closest_user_indices:
    temp = pd.DataFrame(df.iloc[idx])
    print(temp[:].index)
temp.head()

Index(['user_1', 'user_659', 'user_660', 'user_661', 'user_662'], dtype='object')


song_1  song_2  song_3  song_4  song_5  song_6  song_7  song_8  \
user_1         2       2       8       8      13       1       4       9   
user_659       3       9      12      10       2      11      13       1   
user_660       9      11      13      11       5      10       2       0   
user_661       1       6       8       5       3      13       0       0   
user_662       8       6      12       9       8       7       8      15   

          song_9  song_10  ...  song_4991  song_4992  song_4993  song_4994  \
user_1         1        2  ...         14          2         14          1   
user_659       6        3  ...          0          8          1         11   
user_660       5       15  ...         14         10         12          3   
user_661       9        3  ...          6          3          5         13   
user_662      11        3  ...         15          9          6          6   

          song_4995  song_4996  song_4997  song_4998  song_4999  song_5000  
user_1            9          0         11          6         14          7  
user_659         12          5          2          7          3          2  
user_660         15          2         14          0         13         12  
user_661         10         14          2          4          5         10  
user_662         12          1          3         13         13          4  

[5 rows x 5000 columns]

# Implimentaion of K-means

In [36]:
# Assume that user1 is listening to song1
# Following are steps for K-means
# Define the number of cluster for different song k=10

In [37]:
k= 10
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters= k)
kmeans.fit(song_matrix)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=10, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [38]:
# Find which cluster song belong
# Find vector for song 1
indexin_df = list(df.columns).index('song_1')

In [39]:
print(indexin_df)

0


In [40]:
song1_vec = song_matrix[indexin_df]
kmeans.predict([song1_vec])

array([1])

In [41]:
song_matrix.shape

(5000, 100)

In [42]:
cluster_id = 8
allLabels = list(kmeans.predict(song_matrix))
predicted_cluster_id = [idx for idx in range(len(allLabels)) if allLabels[idx == cluster_id]]
predicted_cluster_candidate = song_matrix[predicted_cluster_id]
print(predicted_cluster_candidate)

[[0.09111663 0.04599194 0.35443294 ... 0.33335427 0.         0.        ]
 [0.17234709 0.09042347 0.04767831 ... 0.16380215 0.16382856 0.18483858]
 [0.34858481 0.14847774 0.46616122 ... 0.         0.17891825 0.12377252]
 ...
 [0.03672748 0.13177138 0.4128003  ... 0.07299475 0.18730326 0.06243832]
 [0.29720103 0.         0.30755414 ... 0.36621594 0.         0.        ]
 [0.         0.         0.         ... 0.29195844 0.09004042 0.        ]]


In [43]:
from sklearn.neighbors import NearestNeighbors
KNN = NearestNeighbors(n_neighbors= 5)
KNN.fit(predicted_cluster_candidate)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=None, n_neighbors=5, p=2, radius=1.0)

In [44]:
KNN.kneighbors([song_matrix[indexin_df]])

(array([[0.        , 1.84778829, 1.85746931, 1.88433517, 1.89436169]]),
 array([[   0,  564, 3927, 4490, 4736]], dtype=int64))